#!/bin/bash
# Read input from command line arguments or standard input
if [ $# -gt 0 ]; then
    input=$*
else
    read -r input
fi
# Reverse the input using the rev command
output=$(echo "$input" | rev)
