#!/bin/bash
src_dir=$(pwd); dest_dir=$(dirname "$src_dir"); for file in "$src_dir"/*.html; do filename=$(basename "$file"); if [[ ! -e "$dest_dir/$filename" || "$file" -nt "$dest_dir/$filename" ]]; then cp "$file" "$dest_dir"; echo "Copied $filename to $dest_dir"; fi; done
