#!/usr/bin/env bash
# Bash script that displays to infinity and message in case of SIGTERM 
message() {
	echo "I am invincible!!!"
}
trap message SIGTERM
while (true)
do
	echo "To infinity and beyond"
	sleep 2
done
