#!/usr/bin/env bash
# Running nginx as nginx user and master process
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod -R u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
